image: python:3.12.4

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1

cache:
  paths:
    - .cache/pip

stages:
  - test

test:
  stage: test
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pre-commit
  script:
    - pre-commit run --all-files
    - python -m pytest
