version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: devenv
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
